### ISSUE TITLE
Lookahead problem

### ISSUE THREAD

**Issue by rbri** [codelibs/nekohtml#8]
Hi all,

we are facing a serious problem with our Neko fork - https://github.com/HtmlUnit/htmlunit-neko/pull/98
As far as i can see, the same code is also in use in your code. Maybe you like to have a look and apply this fix also (and the test).

For some more info you can also have a look at https://x.com/HtmlUnit/status/1768703981914591257?s=20

**Comment by marevol** [comment]
Thank you for the info. Fixed in f0a17d737211c58f1f69333d2f3f364baff26378.
